version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless@1.34.1
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - cp ./.serverless/serverless-webpack-starter.zip .      

artifacts:
  files:   
    - appspec.yml
    - serverless-webpack-starter.zip