version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless@1.34.1
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:   
    .serverless/serverless-webpack-starter.zip