version: 0.2

phases:
  install:
    commands:
      - npm install -g serverless@1.34.1
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - move ./.serverless/serverless-webpack-starter.zip ./serverless-webpack-starter.zip

artifacts:
  files:   
    - serverless-webpack-starter.zip